import { Platform } from "react-native";

var english = {
  error_msg:
    "This operation is taking too long due to a poor connection. Do you wish to cancel it?",
  int_option1: "CANCEL",
  int_option2: "WAIT",
  no_internet: "Not connected to the internet",
  //login labels start
  welcome: "WELCOME!",
  login: "Login",
  signup: "Create a FREE one !",
  forgot_password: "Forgot User ID or Password?",
  show_password: "Show Password",
  placeholder_username: "Username",
  placeholder_password: "Password",
  error_username_msg: "Please Enter Username",
  error_password_msg: "Please Enter Password",
  error_invalid_login_msg: "Sorry , Invalid Username or Password",
  no_acount_labels: "Don't Have an Account?",
  forgotLabel: "SORRY",
  forgotmsg: "We could not find that record. Please try again.",
  forgotsuccess: "SUCCESS",
  forgotsuccessmsg: "We have texted your User ID and Password to your phone.",
  subscribeFor: "Subscribe for",
  //login labels end
  //Signup labels start
  placeholder_firstname: "First Name ",
  placeholder_cellphone: "Cell Number ",
  placeholder_country: "Cellular Country Code ",
  error_company_name_msg: "Please Enter Company Name",
  error_first_name_msg: "Please Enter First Name",
  error_country_code_msg: "Please Select Country code",
  error_cellphone_msg: "Please Enter Cellphone no.",
  error_last_name_msg: "Please Enter Last Name",
  error_cell_number_msg: "Please Enter Cell Number",
  error_store_number: "Please Enter Store Number",
  error_address_msg: "Please Enter Address",
  error_city_msg: "Please Enter City",
  error_state_msg: "Please Enter State",
  error_zip_msg: "Please Enter Zip Code",
  error_email_msg: "Please Enter Email",
  error_pwd_emp_msg: "Please Enter Password For Employee",
  error_associated_id_msg: "Please Enter Associated ID",
  error_del_charge_msg: "Please Enter Delivery Charges",
  error_tax_msg: "Please Enter Tax Rate",
  label_continue: "Continue",
  //signup labels end

  //Screen title start
  orders: "Orders",
  inventory: "Add",
  profile: "Profile",
  search: "Search",
  share: "Share",
  createorder: "Create Order",
  login: "Login",

  //screen title end

  logout: "Logout",
  submit: "Submit",
  already: "Already Have Account? ",
  loginhere: "Login Here",

  //profile

  placeholder_company_name: "Company Name *",
  placeholder_first_name: "First Name *",
  placeholder_last_name: "Last Name *",
  placeholder_cell_phone: "Cell Number *",
  placeholder_store_phone: "Store Phone *",
  placeholder_offer_delivery: "Do you offer delivery?",
  placeholder_offer_dinin:"Allow Dine In ordering?",
  placeholder_hours_of_operation: "Hours of Operation",
  placeholder_address: "Address *",
  placeholder_city: "City *",
  placeholder_state: "State ",
  placeholder_zip: "Zip*",
  placeholder_email: "Email *",
  placeholder_passwordp: "Password *",
  placeholder_password_for_emp: "Employee Password *",
  placeholder_Assosiated_id: "Associate ID",
  placeholder_deliver: "Delivery Charge",
  placeholder_rate: "Tax Rate",
  placeholder_autogratuity: "Gratuity / Service Charge",
  placeholder_bussinesstype: "Business Type *",
  bussinesstype_option0: "--select--",
  bussinesstype_option1: "All others",
  bussinesstype_option2: "Restaurant",
  placeholder_term: "Terms, Conditions, Instructions ",
  your_locationid: "Your location ID:",
  your_web_site: "Your website link:",
  stateprovince: "State / Province *",
  //add inventory
  placeholder_producttitle: "Product Title",
  placeholder_master_cat: "Master Category",
  addmore: "Add",
  placeholder_subcat1: "Sub Category 1",
  placeholder_subcat2: "Sub Category 2",
  placeholder_searchtag: "Add Search Tags (Comma between words)",
  placeholder_desc: "Product Description",
  placeholder_quantity: "Quantity",
  placeholder_price: "Price",
  placeholder_cost: "Cost",
  addinvetory: "ADD ITEM TO STOCK",
  placeholder_supplier: "Supplier",
  placeholder_location: "Location in Shop",
  placeholder_unit: "Unit",
  placeholder_size: "Size",
  placeholder_color: "Color",
  placeholder_sku: "Barcode",
  inventoryaddmsg: "SUCCESS! Your stock # is: ",
  confirmmsg: "Do you want to save this record?",
  confirmmsg1: "Do you want to save these changes?",
  confirmoption1: "YES",
  confirmoption2: "NO",
  confirmoption3: "CANCEL",
  // add inventory error massages
  add_product: "ADD PRODUCT",
  placeholder_attachbacode: "ATTACH BARCODE",
  placeholder_barcode_attached: "Barcode Attached",
  error_product_title: "Please enter product title",
  error_mastercat: "Please select main category",
  error_sub1_str: "Please select sub Category",
  error_sub2_str: "Please select sub Category",
  error_searchtag: "Please enter search tags",
  error_product_desc: "Please enter product description",
  error_quantity: "Please enter quantity",
  error_price: "Please enter price",
  error_cost: "Please cost",
  error_supplier_str: "Please select supplier",
  error_location_str: "Please select location",
  error_unit_str: "Please select unit",
  error_size_str: " Please select size",
  error_color_str: "Please select color",
  error_sku: "Please enter SKU PVT Notes",
  alert_imdone: "I'm Done",
  alert_copy: "Copy to New Record",
  alert_new: "Add New Record",
  label_add: "ADD",
  label_addentry:'Add entry now',
  label_cancel: "Cancel",
  //dashboard
  active_order: "Active Orders",
  subjectline_for_share: " has shared an item with you",
  in_stock: "In Stock",
  out_stock: "Out of Stock",
  kizbin_viewing: "Kizbin Viewing",
  kizbin_orders: "Kizbin Orders",
  this_week: "This Week",
  to_date: "To Date",
  add_inventory: "Add",
  home:'Home',
  search_inventory: "Search",
  orders: "Orders",
  your_profile: "Profile",
  share_your_site: "Share",
  create_order: "Create Order",
  out_of_stock: "Out of Stock Products",
  cout_in_stock: "In Stock",
  share_msg_shop: "invites you to view and order from them online. Visit:",
  // Search screen
  placeholder_search: "SEARCH INVENTORY",
  placeholder_scanebarcode: "SCAN BARCODE",
  placeholder_keywords: "Keywords (Use comma between words)",
  placeholder_stocknumber: "Stock Number ",
  placeholder_master: "Master Category (This Location Only)",
  confirm_delete_msg: "Do you really want to delete this record?",
  confirm_share_msg: "Do you really want to share this product?",
  placeholder_inventory: "SEARCH RESULTS",
  subtraction_stock: "Insufficient stock",
  placeholder_searchthis: "SEARCH THIS LOCATION",
  placeholder_city_name: "City",
  placeholder_company: "Company Name",
  placeholder_phone_no: "Phone number",
  sortby: "Sortby",
  itemfound: "Items",
  sharemsg: "has shared an item you may be interested in. Please visit: ",
  placeholder_searchlocation: "SEARCH ALL LOCATIONS",
  placeholder_searchclear: "CLEAR SEARCH",
  sortcategory: "Sort by: Category",
  longest: "Longest",
  latest: "Latest",
  pricehtl: "Price (High to low)",
  pricelth: "Price (Low to high)",
  price: "Price",
  cost: "Cost",
  supplier: "Supplier",
  location: "Location",
  size: "Size",
  color: "Color",
  editinvetory: "Edit Inventory",
  sharebtn: "Share",
  deletebtn: "Delete",
  editbtn: "Edit",
  search_company: "Company",
  search_city: "City",
  search_phone: "Phone number",
  alert: "Alert",
  search_barecodenotfound: "No Barcode Found",
  edit_success_label: "Record updated!",
  //order labels
  order_search_label: "# Order, Phone or Name",
  order_latest: "Latest",
  order_waiting: "Waiting",
  order_progress: "In progress",
  order_closed: "Closed",
  order_deleted: "Delete this Order",

  order_div: "Dine-in",
  order_delivery: "Delivery",
  order_pickup: "Pickup",
  order_reciept: "Receipt",
  order_inbasket: "In Basket",

  order_name: "Name",
  order_email: "Email",
  order_payment: "Payment Type",
  order_company: "Company",
  order_address: "Address",
  order_city: "City",
  order_state: "State/Prov",
  order_zip: "Zip/Postal",
  order_country: "Country",
  order_factura: "Factura",
  order_factura_msg: "Factura Requested",

  order_company_name:"Name or Company",
  order_number_street:"Address",
  order_cologne:"Neighbourhood",
  order_municiplity:"City",
  order_postalcode:"Postal",
  order_rfc:"R.F.C",
  order_email:"Email",

  order_note: "Customer Notes:",
  order_viewinmap: "View In Maps",
  order_cust_name: "Name",
  order_time: "Time",
  order_time_table: "Table",
  order_value: "Order Value",
  order_phone: "Phone",
  order_ready: "Ready",
  order_delivery_instruction: "Send Delivery Instruction",
  printlabel: "Print Order",
  share_instrcution0: "An Order is Ready",
  share_instrcution1: "Order #",
  share_instrcution2: "is ready for delivery. ",
  //subscription
  dash_subscription: "Get Subscription",
  dash_try: "Continue with trial",
  subs_anual: "$499/- per Year",
  subs_monthly: "$49/- per Month",
  isexist:
    "This number has an account. Please select a different cell number to create an account.",
    success:'Success',
    isexistbarcode: "Order has been deleted",

  //profile alerts
  alert_emp_password:
    "This password will limit the user to viewing inventory and processing orders.",
  alert_assoc:
    "This field allows multiple locations to view a group inventory. Enter ONE of the 4 letter location IDs in ALL of the profiles of the accounts you wish to link together.",
  alert_delivery:
    "If you charge for delivery, it will be displayed to your customer on the order page and on the printed order form.",
  alert_tax:
    "If you charge tax, the amount will be displayed to your customer on the order page and on the printed order form.",
  alert_grativity:
    "If you charge for Gratuity or Service, it will be displayed to your customer on the order page and on the printed order form.",
  alert_term:
    "These notes will appear to your customers on your order page and on the printed receipt.",
  login_usertype_manager_alert:
    "You are logging in with a management level password. A subscription is required. Contact your manager for an employee level password to use the app for free.",
  continue_login: "Continue with Login",
  login_usertype_employee_alert:
    "You are logging with an employee level password. This version has limited functionality and is free of charge. Contact your manager for a management level password.",
  //subscription screen
  have_not: "Have an Account? Login Here",
  NoAccount: "No Account? Create one.",
  trail30: "First 30 Days Are FREE!",
  cancelsubs:
    "Cancel anytime before or after your trial. Select a plan to continue.",
  month: "Month",
  year: "Year",
  saved: "(12 months at $29.00/mo.)",
  save: "SAVE 25%",
  purchase: "Restore your Purchase",
  flowdesc1: `• After the 30-day free trial, payment will be charged to ${Platform.OS === "android" ? "Google" : "iTunes"
    } Account in your local currency at confirmation of purchase.`,
  flowdesc2:
    "• Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period.",
  flowdesc3:
    "• Account will be charged for renewal within 24-hours prior to the end of the current period as per the price shown on our website.",
  flowdesc4:
    "• Subscriptions may be managed, and auto-renewal may be turned off by going to your Account Settings after purchase.",
  terms: "Terms of Service",
  privacy: "Privacy Policy",
  profileDescription1: "Most of the functionality offered by the app is available on our website ",
  profileDescription2: ". Use the same username and password to access your account.",
  profileDescription3: "To upload your logo",
  profileDescription4: "1)	Log in to your account here: ",
  profileDescription5: "2)	Click on the Profile link ",
  profileDescription6: "3)	Click on Upload Logo ",
  //payment failed screen
  iTunes: `• Payment will be charged ${Platform.OS === "android" ? "Google" : "iTunes"} Account inlocal currency at confirmation of purchase.`,
  subscription: `• Subscription automatically renews unless auto-renew is turned off at lease 24-hours before the current period.`,
  account24: `• Account will be charged for renewal within 24-hours prior to the end of the current period as per the price shown in our website.`,
  subsmanage: `• Subscriptions may be managed, and auto-renewal may be turned off by going to your Account Settings after purchase.`,
  restoremsg: "Restore your Purchase",
  problem: `There was a problem with your ${Platform.OS === "android" ? "Google" : "iTunes"} account.`,
  gotologin: "Go to Login Page",
  //trial screen
  trialalert1: `Your Free Trial is ending in `,
  trialalert2: "days!",
  toprogram: `Continue with the program`,
  managesubs: `Manage your subscription`,
  selectCont: `• By selecting Continue with the program, you can continue as normal. Payment will be charged to iTunes Account in local currency .`,
  autoRenew: `• Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period.`,
  chargerenew: `• Account will be charged for renewal within 24-hours prior to the end of the current period as per the price shown on our website.`,
  managerenew: `• Subscriptions may be managed, and auto-renewal may be turned off by going to your Account Settings after purchase.`,
  mastercategories:`Master categories are shown on your website alphabetically. Number the category to change the order. EG: 1 Appetizer. The numerals will not be seen by customers.`,
  OrderDetailsInStock:'In Stock',
  OrderDetailsOrders:'Orders',
  OrderDetailsStock:'Stock No.',
  OrderDetailsColor:'Color',
  OrderDetailsSize:'Size'
};



















// Spanish Language
var spanish = {
  error_msg:
    "Esta operación está tardando demasiado debido a una mala conexión.  ¿Deseas cancelarlo?",
  int_option1: "CANCELAR",
  int_option2: "ESPERAR",
  no_internet: "No conectado a internet",
  //login labels start
  welcome: "BIENVENIDOS",
  login: "Iniciar sesión",
  signup: "Crea una GRATIS",
  forgot_password: "Olvidé mi  Usuario o Contraseña",
  show_password: "Mostrar Contraseña",
  placeholder_username: "Nombre de Usuario",
  placeholder_password: "Contraseña",
  error_username_msg: "Por Favor Ingrese Usuario",
  error_password_msg: "Por Favor, Ingrese Contraseña",
  error_invalid_login_msg: "Lo Sentimos, el Usuario o Contraseña no Válidos",
  no_acount_labels: "No Tienes Cuenta?",
  forgotLabel: "LO SIENTO",
  forgotmsg: "No pudimos encontrar ese registro. Inténtalo de nuevo.",
  forgotsuccess: "ÉXITO",
  forgotsuccessmsg:
    "Hemos enviado un mensaje de texto con su Usuario y Contraseña a su teléfono.",
  subscribeFor: "Subscribe por",
  //login labels end

  //Signup labels start

  placeholder_firstname: "Nombre",
  placeholder_cellphone: "Numero de Celular",
  placeholder_country: "Código Celular del País",
  error_company_name_msg: "Por favor, introduzca el Nombre de la Empresa",
  error_first_name_msg: "Por favor, introduzca tu nombre",
  error_country_code_msg: "Por favor seleccione tu código del país",
  error_cellphone_msg: "Por favor, introduzca tu número de teléfono móvil.",
  error_last_name_msg: "Por favor, introduzca tu apellido",
  error_cell_number_msg: "Por favor, introduzca tu número de celular",
  error_store_number: "Por favor, introduzca el número de tienda",
  error_address_msg: "Por favor, introduzca la dirección",
  error_city_msg: "Por favor, introduzca la ciudad",
  error_state_msg: "Por favor, introduzca el estado",
  error_zip_msg: "Por favor, introduzca el código postal",
  error_email_msg: "Por favor, introduzca tu correo electrónico",
  error_pwd_emp_msg: "Por favor, introduzca la contraseña para el empleado",
  error_associated_id_msg: "Por favor, introduzca el código de asociada",
  error_del_charge_msg: "Por favor, introduzca los gastos de envío",
  error_tax_msg: "Por favor, introduzca la tasa de impuestos",
  label_continue: "Continuar",

  //signup labels end

  //Screen title start
  orders: "Ordenes",
  inventory: "Agregar",
  profile: "Perfil",
  search: "Buscar",
  login: "Iniciar Sesión",
  share: "Compartir",
  createorder: "Crear Orden",
  //screen title end

  logout: "Cerrar Sesión",
  submit: "ENVIAR",
  already: "¿Ya Tienes Cuenta?",
  loginhere: "Iniciar Sesión",

  placeholder_company_name: "Nombre de Empresa *",
  placeholder_first_name: "Nombre *",
  placeholder_last_name: "Apellido *",
  placeholder_cell_phone: "Numero de Celular *",
  placeholder_store_phone: "Teléfono de Tienda *",
  placeholder_address: "Dirección *",
  placeholder_city: "Ciudad *",
  placeholder_state: "Estado",
  placeholder_zip: "Código Postal *",
  placeholder_email: "Correo Electrónico *",
  placeholder_passwordp: "Contraseña *",
  placeholder_password_for_emp: "Contraseña del Empleado *",
  placeholder_Assosiated_id: "Código de Asociada",
  placeholder_deliver: "Cargo de Envío",
  placeholder_offer_delivery: "Ofrecen entrega?",
  placeholder_offer_dinin:"Permitir comer aqui?",
  placeholder_hours_of_operation: "Horas de operación",
  placeholder_rate: "Tasa de Impuesto",
  placeholder_autogratuity: "Propina / Cargo por Servicio",
  placeholder_bussinesstype: "Tipo de Negocio *",
  bussinesstype_option0: "--SELECCIONE--",
  bussinesstype_option1: "Todos los demas",
  bussinesstype_option2: "Restaurante",
  placeholder_term: "Términos, Condiciones, Instrucciones",
  your_locationid: "Usuario",
  your_web_site: " Tu Enlace Web",
  stateprovince: "Provincia o Estado *",
  //add inventory
  add_product: "AGREGAR PRODUCTO",
  placeholder_attachbacode: "COLOCAR EL CÓDIGO DE BARRAS",
  placeholder_barcode_attached: "Código de Barras Adjunto",
  placeholder_producttitle: "Titulo del Producto",
  placeholder_master_cat: "Categoría Principal",
  addmore: "Agregar",
  placeholder_subcat1: "Subcategoría 1",
  placeholder_subcat2: "Subcategoría 2",
  placeholder_searchtag: "Agregar Etiquetas de Búsqueda (coma entre palabras)",
  placeholder_desc: "Descripción del Producto",
  placeholder_quantity: "Cantidad",
  placeholder_price: "Precio",
  placeholder_cost: "Costo",
  addinvetory: "AGREGA EL ARTÍCULO",
  placeholder_supplier: "Proveedor",
  placeholder_location: "Ubicación en la Tienda",
  placeholder_unit: "Unidad",
  placeholder_size: "Talla",
  placeholder_color: "Color",
  placeholder_sku: "Barras",
  inventoryaddmsg: "¡ÉXITO! El Numero Inventario es: ",
  alert_imdone: "He Terminado",
  alert_copy: "Copiar a Nuevo Registro",
  alert_new: "Agragar Nuevo Registro",
  confirmmsg: "¿Quieres guardar este registro?",
  confirmmsg1: "¿Quieres guardar estas cambios?",
  confirmoption1: "SI",
  confirmoption2: "NO",
  confirmoption3: "CANCELAR",
 
  label_add: "AGREGA ",
  label_addentry:'Agrega registro ahora',
  label_cancel: "CANCELAR",
  // add inventory error massages
  error_product_title: "Por favor, introduzca el título del producto",
  error_mastercat: "Por favor seleccione la categoría principal",
  error_sub1_str: "Por favor seleccione subcategoría",
  error_sub2_str: "Por favor seleccione subcategoría",
  error_searchtag: "Por favor, introduzca las etiquetas de búsqueda",
  error_product_desc: "Por favor, introduzca la descripción del producto",
  error_quantity: "Por favor ingrese la cantidad",
  error_price: "Por favor ingrese el precio",
  error_cost: "Por favor ingrese costo",
  error_supplier_str: "Por favor seleccione proveedor",
  error_location_str: "Por favor seleccione ubicación",
  error_unit_str: "Por favor seleccione unidad",
  error_size_str: "Por favor seleccione un tamaño",
  error_color_str: "Por favor seleccione color",
  error_sku: "Por favor, introduzca SKU Notas Privadas",

  //dashboard
  active_order: "Pedidos",
  subjectline_for_share: " ha compartido un artículo contigo",
  in_stock: "Inventario",
  out_stock: "Agotado",
  kizbin_viewing: "Visitas de Kizbin",
  kizbin_orders: "Órdenes de Kizbin",
  this_week: "Esta Semana",
  to_date: "Hasta la Fecha",
  add_inventory: "Agregar",
  home:'Inicio',
  search_inventory: "Buscar",
  orders: "Ordenes",
  your_profile: "Perfil",
  share_your_site: "Compartir",
  create_order: "Crear Orden",
  out_of_stock: "Productos Agotados",
  cout_in_stock: "En Inventario",
  share_msg_shop: "lo invita a ver y ordenar en línea. Visita: ",
  // Search screen
  placeholder_search: "BUSCAR INVENTARIO",
  placeholder_scanebarcode: "ESCANEAR CÓDIGO DE BARRAS",
  placeholder_keywords: "Palabras Clave (Use comas entre palabras)",
  placeholder_stocknumber: "Número de Inventario ",
  placeholder_master: "Categoría Principal (solo esta ubicación)",
  confirm_delete_msg: "¿Realmente quieres eliminar este registro?",
  confirm_share_msg: "¿De verdad quieres compartir este producto?",
  placeholder_inventory: "RESULTADOS",
  placeholder_searchthis: "BUSCA ESTA UBICACIÓN",
  subtraction_stock: "Insufficient Stock",
  placeholder_searchlocation: "BUSCAR TODAS LAS UBICACIONES",
  placeholder_searchclear: "BORRAR BÚSQUEDA",

  sortby: "Ordenar por",
  itemfound: "Articulos Encontrado",
  sharemsg: "ha compartido un artículo que puede interesarle. Visite: ",
  sortcategory: "Ordenar: Categoria",
  longest: "Más Largo",
  latest: "Último",
  pricehtl: "Precio (mayor a menor)",
  pricelth: "Precio (menor a mayor)",
  price: "Precio",
  cost: "Costo",
  supplier: "Proveedor",
  location: "Ubicación",
  size: "Talla",
  color: "Color",
  editinvetory: "Editar Inventario",
  sharebtn: "Compartir",
  deletebtn: "Eliminar",
  editbtn: "Editar",
  search_company: "Nombre de Empresa",
  search_city: "Ciudad",
  search_phone: "Número de Teléfono",
  alert: "Alerta",
  search_barecodenotfound: "No Se Encontró Código de Barras.",
  edit_success_label: "Registro actualizado!",
  //order labels
  order_search_label: "# Orden, Teléfono, Nombre",
  order_latest: "Último",
  order_waiting: "Esperando",
  order_progress: "En Progreso",
  order_closed: "Cerrado",
  order_deleted: "Eliminar este Pedido",
  order_ready: "Listo",
  order_div: "Comer Aqui",
  order_delivery: "Entrega",
  order_pickup: "Recoger",
  order_reciept: "Recibo",
  order_inbasket: "Orden",

  order_name: "Nombre",
  order_email: "Correo Electrónico",
  order_payment: "Tipo de Pago",
  order_company: "Empresa",
  order_address: "Dirección",
  order_city: "Ciudad",
  order_state: "Estado",
  order_zip: "Código Postal",
  order_country: "País",
  order_factura: "Factura",
  order_factura_msg: "Factura Requerida",

  order_company_name:"Nombre o Empresa",
  order_number_street:"Numero y Calle",
  order_cologne:"Colonia",
  order_municiplity:"Municipio",
  order_postalcode:"Codigo Postal",
  order_rfc:"R.F.C",
  order_email:"Correo Electronico",

  order_note: "Notas de los Clientes:",
  order_viewinmap: "Ver en el Mapa",
  order_cust_name: "Nombre",
  order_time: "Mesa",
  order_time_table: " Hora y Mesa",
  order_value: "Valor del Pedido",
  order_phone: "Teléfono",
  order_delivery_instruction: "Envia Instrucciones de Entrega",
  printlabel: "Imprime el Pedido",
  share_instrcution0: "Un Pedido Esta Listo",
  share_instrcution1: "El pedido de Kizbin  #",
  share_instrcution2: "está listo para su entrega.",
  //subscription
  dash_subscription: "Get Subscription",
  dash_try: "Continue with trial",
  subs_anual: "$499/- per Year",
  subs_monthly: "$49/- per Month",
  isexist:
    "Este número tiene una cuenta. Seleccione un número de celular diferente para crear una cuenta.",
  success:'Éxito',
    isexistbarcode: "El pedido ha sido eliminado",

  //profile alerts
  alert_emp_password:
    "Esta contraseña limitará al usuario a ver el inventario y procesar pedidos.",
  alert_assoc:
    "Este campo permite múltiples ubicaciones para ver un inventario grupal. Ingrese UNO usuario de 4 letras en TODOS los perfiles de las cuentas que deseas vincular",
  alert_delivery:
    "Si cobras por la entrega, se mostrará a su cliente en la página de pedido y en el formulario de pedido impreso.",
  alert_tax:
    "Si cobras impuestos, el monto se mostrará a su cliente en la página del orden y en el formulario de pedido impreso.",
  alert_grativity:
    "Si cobras una propina o servicio, se mostrará a su cliente en la página del orden y en el formulario de pedido impreso",
  alert_term:
    "Estas notas aparecerán para sus clientes en la página de su pedido y en el recibo impreso.",
  login_usertype_manager_alert:
    "Estás iniciando sesión con una contraseña de nivel de administración. Se requiere una suscripción. Póngase en contacto con su gerente para obtener una contraseña de nivel de empleado para usar la aplicación de forma gratuita.",

  continue_login: "Continuar con inicio de sesión",

  login_usertype_employee_alert:
    "Está iniciando sesión con una contraseña de nivel de empleado. Esta versión tiene una funcionalidad limitada y es gratuita. Póngase en contacto con su gerente para obtener una contraseña de nivel de administración.",
  profileDescription1: "La mayor parte de las funciones que ofrece la aplicación están disponibles en nuestro sitio web ",
  profileDescription2: ". Utilice el mismo usuario y contraseña para acceder a su cuenta.",
  profileDescription3: "Para cargar su logotipo",
  profileDescription4: "1) Inicie sesión en su cuenta aquí: ",
  profileDescription5: "2) Haga clic en el enlace Perfil ",
  profileDescription6: "3) Haga clic en Subir Logotipo ",

  //subscription screen
  have_not: "¿Tienes una cuenta? Entre Aquí",
  NoAccount: "¿No tienes cuenta? Crea una.",
  trail30: "¡Los Primeros 30 Días Son GRATIS!",
  cancelsubs:
    "Cancele en cualquier momento antes o después de su prueba. Seleccione un plan para continuar.",
  month: "Mes",
  year: "Año",
  saved: "(12 meses por $29.00/mes.)",
  save: "AHORRA 25%",
  purchase: "Restaura Tu Compra",
  flowdesc1: `• Después de la prueba gratuita de 30 días, el pago se cargará a la cuenta de ${Platform.OS === "android" ? "Google" : "iTunes"
    } en su moneda local en la confirmación de la compra.`,
  flowdesc2:
    "• La suscripción se renueva automáticamente a menos que la renovación automática se desactive al menos 24 horas antes del final del período actual.",
  flowdesc3:
    "• Se cobrará a la cuenta la renovación dentro de las 24 horas anteriores al final del período actual según el precio que se muestra en nuestro sitio web.",
  flowdesc4:
    "• Las suscripciones se pueden administrar y la renovación automática se puede desactivar yendo a la Configuración de su cuenta después de la compra.",
  terms: "Términos de servicio",
  privacy: "Términos de privacidad ",
  //payment failed screen
  iTunes: `• Después de la prueba gratuita de 30 días, el pago se cargará a la cuenta de ${Platform.OS === "android" ? "Google" : "iTunes"
    } en su moneda local en la confirmación de la compra.`,
  subscription: `• La suscripción se renueva automáticamente a menos que la renovación automática se desactive al menos 24 horas antes del final del período actual.`,
  account24: `• Se cobrará a la cuenta la renovación dentro de las 24 horas anteriores al final del período actual según el precio que se muestra en nuestro sitio web.    `,
  subsmanage: `• Las suscripciones se pueden administrar y la renovación automática se puede desactivar yendo a la Configuración de su cuenta después de la compra.`,
  restoremsg: "Restore your Inicio de Sesión",
  problem: `Hubo un problema con tu cuenta de ${Platform.OS === "android" ? "Google" : "iTunes"
    }.`,
  gotologin: "Inicio de Sesión",
  //trial screen
  trialalert1: `Su prueba gratuita caduca en`,
  trialalert2: "días!",

  toprogram: `Continuar con el Programa`,
  managesubs: `Administre su Suscripción`,
  selectCont: `• Después de la prueba gratuita de 30 días, el pago se cargará a la cuenta de iTunes en su moneda local.`,
  autoRenew: `• La suscripción se renueva automáticamente a menos que la renovación automática se desactive al menos 24 horas antes del final del período actual.`,
  chargerenew: `• Se cobrará a la cuenta la renovación dentro de las 24 horas anteriores al final del período actual según el precio que se muestra en nuestro sitio web.`,
  managerenew: `• Las suscripciones se pueden administrar y la renovación automática se puede desactivar yendo a la Configuración de su cuenta después de la compra.`,
  mastercategories:`Las categorías principales se muestran en su sitio web en orden alfabético. Numere la categoría para cambiar el orden. Por ejemplo: 1 aperitivo. Los clientes no verán los números.`,
  OrderDetailsInStock:'en inventario',
  OrderDetailsOrders:'Cantidad',
  OrderDetailsStock:'# Inventario',
  OrderDetailsColor:'Color',
  OrderDetailsSize:'Tamaño'
};

export { spanish, english };
